// Exhaustive version-string exercise: every interface version string shipped
// in any Steamworks SDK from v1.0 to v1.65 is requested through the emulator's
// generic interface dispatch and must return a non-NULL pointer.
#include "sdk_includes/steam_api.h"
#include "sdk_includes/steam_gameserver.h"
#include <cstdio>
#include <cstring>

static int failures = 0;
static int total = 0;

int main()
{
    SteamErrMsg err;
    if (SteamAPI_InitEx(&err) != k_ESteamAPIInitResult_OK) { std::printf("init failed\n"); return 2; }
    SteamGameServer_Init(0, 27015, 27016, eServerModeNoAuthentication, "1.0.0.0");
    SteamGameServer()->LogOnAnonymous();

    const char *versions[] = {
        "STEAMAPPLIST_INTERFACE_VERSION001",
        "STEAMAPPS_INTERFACE_VERSION001",
        "STEAMAPPS_INTERFACE_VERSION002",
        "STEAMAPPS_INTERFACE_VERSION003",
        "STEAMAPPS_INTERFACE_VERSION004",
        "STEAMAPPS_INTERFACE_VERSION005",
        "STEAMAPPS_INTERFACE_VERSION006",
        "STEAMAPPS_INTERFACE_VERSION007",
        "STEAMAPPS_INTERFACE_VERSION008",
        "STEAMAPPS_INTERFACE_VERSION009",
        "STEAMAPPTICKET_INTERFACE_VERSION001",
        "STEAMCONTROLLER_INTERFACE_VERSION",
        "STEAMHTMLSURFACE_INTERFACE_VERSION_002",
        "STEAMHTMLSURFACE_INTERFACE_VERSION_003",
        "STEAMHTMLSURFACE_INTERFACE_VERSION_004",
        "STEAMHTMLSURFACE_INTERFACE_VERSION_005",
        "STEAMHTTP_INTERFACE_VERSION001",
        "STEAMHTTP_INTERFACE_VERSION002",
        "STEAMHTTP_INTERFACE_VERSION003",
        "STEAMINVENTORY_INTERFACE_V001",
        "STEAMINVENTORY_INTERFACE_V002",
        "STEAMINVENTORY_INTERFACE_V003",
        "STEAMMUSICREMOTE_INTERFACE_VERSION001",
        "STEAMMUSIC_INTERFACE_VERSION001",
        "STEAMPARENTALSETTINGS_INTERFACE_VERSION001",
        "STEAMREMOTEPLAY_INTERFACE_VERSION001",
        "STEAMREMOTEPLAY_INTERFACE_VERSION002",
        "STEAMREMOTEPLAY_INTERFACE_VERSION003",
        "STEAMREMOTEPLAY_INTERFACE_VERSION004",
        "STEAMREMOTESTORAGE_INTERFACE_VERSION002",
        "STEAMREMOTESTORAGE_INTERFACE_VERSION004",
        "STEAMREMOTESTORAGE_INTERFACE_VERSION005",
        "STEAMREMOTESTORAGE_INTERFACE_VERSION008",
        "STEAMREMOTESTORAGE_INTERFACE_VERSION010",
        "STEAMREMOTESTORAGE_INTERFACE_VERSION012",
        "STEAMREMOTESTORAGE_INTERFACE_VERSION013",
        "STEAMREMOTESTORAGE_INTERFACE_VERSION014",
        "STEAMREMOTESTORAGE_INTERFACE_VERSION016",
        "STEAMSCREENSHOTS_INTERFACE_VERSION001",
        "STEAMSCREENSHOTS_INTERFACE_VERSION002",
        "STEAMSCREENSHOTS_INTERFACE_VERSION003",
        "STEAMTIMELINE_INTERFACE_V001",
        "STEAMTIMELINE_INTERFACE_V004",
        "STEAMUGC_INTERFACE_VERSION001",
        "STEAMUGC_INTERFACE_VERSION002",
        "STEAMUGC_INTERFACE_VERSION003",
        "STEAMUGC_INTERFACE_VERSION005",
        "STEAMUGC_INTERFACE_VERSION007",
        "STEAMUGC_INTERFACE_VERSION008",
        "STEAMUGC_INTERFACE_VERSION009",
        "STEAMUGC_INTERFACE_VERSION010",
        "STEAMUGC_INTERFACE_VERSION012",
        "STEAMUGC_INTERFACE_VERSION014",
        "STEAMUGC_INTERFACE_VERSION015",
        "STEAMUGC_INTERFACE_VERSION016",
        "STEAMUGC_INTERFACE_VERSION017",
        "STEAMUGC_INTERFACE_VERSION018",
        "STEAMUGC_INTERFACE_VERSION020",
        "STEAMUGC_INTERFACE_VERSION021",
        "STEAMUNIFIEDMESSAGES_INTERFACE_VERSION001",
        "STEAMUSERSTATS_INTERFACE_VERSION003",
        "STEAMUSERSTATS_INTERFACE_VERSION004",
        "STEAMUSERSTATS_INTERFACE_VERSION005",
        "STEAMUSERSTATS_INTERFACE_VERSION006",
        "STEAMUSERSTATS_INTERFACE_VERSION007",
        "STEAMUSERSTATS_INTERFACE_VERSION009",
        "STEAMUSERSTATS_INTERFACE_VERSION010",
        "STEAMUSERSTATS_INTERFACE_VERSION011",
        "STEAMUSERSTATS_INTERFACE_VERSION012",
        "STEAMUSERSTATS_INTERFACE_VERSION013",
        "STEAMVIDEO_INTERFACE_V001",
        "STEAMVIDEO_INTERFACE_V002",
        "STEAMVIDEO_INTERFACE_V007",
        "SteamClient007",
        "SteamClient008",
        "SteamClient009",
        "SteamClient010",
        "SteamClient011",
        "SteamClient012",
        "SteamClient014",
        "SteamClient015",
        "SteamClient016",
        "SteamClient017",
        "SteamClient018",
        "SteamClient020",
        "SteamClient021",
        "SteamClient023",
        "SteamController003",
        "SteamController004",
        "SteamController005",
        "SteamController006",
        "SteamController007",
        "SteamController008",
        "SteamFriends003",
        "SteamFriends004",
        "SteamFriends005",
        "SteamFriends006",
        "SteamFriends007",
        "SteamFriends008",
        "SteamFriends009",
        "SteamFriends011",
        "SteamFriends013",
        "SteamFriends014",
        "SteamFriends015",
        "SteamFriends017",
        "SteamFriends018",
        "SteamGameCoordinator001",
        "SteamGameServer004",
        "SteamGameServer005",
        "SteamGameServer008",
        "SteamGameServer009",
        "SteamGameServer010",
        "SteamGameServer011",
        "SteamGameServer012",
        "SteamGameServer013",
        "SteamGameServer014",
        "SteamGameServer015",
        "SteamGameServerStats001",
        "SteamGameStats001",
        "SteamInput001",
        "SteamInput002",
        "SteamInput005",
        "SteamInput006",
        "SteamInput007",
        "SteamMasterServerUpdater001",
        "SteamMatchGameSearch001",
        "SteamMatchMaking002",
        "SteamMatchMaking004",
        "SteamMatchMaking006",
        "SteamMatchMaking007",
        "SteamMatchMaking008",
        "SteamMatchMaking009",
        "SteamMatchMakingServers001",
        "SteamMatchMakingServers002",
        "SteamMatchMakingServers003",
        "SteamNetworking001",
        "SteamNetworking002",
        "SteamNetworking003",
        "SteamNetworking004",
        "SteamNetworking005",
        "SteamNetworking006",
        "SteamNetworkingMessages002",
        "SteamNetworkingSockets002",
        "SteamNetworkingSockets006",
        "SteamNetworkingSockets008",
        "SteamNetworkingSockets009",
        "SteamNetworkingSockets012",
        "SteamNetworkingSockets013",
        "SteamNetworkingUtils001",
        "SteamNetworkingUtils003",
        "SteamNetworkingUtils004",
        "SteamParties002",
        "SteamUser009",
        "SteamUser010",
        "SteamUser011",
        "SteamUser012",
        "SteamUser013",
        "SteamUser014",
        "SteamUser016",
        "SteamUser017",
        "SteamUser018",
        "SteamUser019",
        "SteamUser020",
        "SteamUser021",
        "SteamUser022",
        "SteamUser023",
        "SteamUtils002",
        "SteamUtils004",
        "SteamUtils005",
        "SteamUtils006",
        "SteamUtils007",
        "SteamUtils008",
        "SteamUtils009",
        "SteamUtils010",
        "SteamUtils011",
    };

    for (auto v : versions) {
        ++total;
        // try both user and gameserver pipes
        void *a = SteamClient()->GetISteamGenericInterface(SteamAPI_GetHSteamUser(), SteamAPI_GetHSteamPipe(), v);
        void *b = SteamClient()->GetISteamGenericInterface(SteamGameServer_GetHSteamUser(), SteamGameServer_GetHSteamPipe(), v);
        if (!a && !b) {
            ++failures;
            std::printf("NULL: %s\n", v);
        }
    }
    SteamAPI_Shutdown();
    std::printf("%d versions requested, %d failed\n", total, failures);
    return failures ? 1 : 0;
}
